defaults:
  -
    values:
      title: Hack Quarantine
      tagline: A global, virtual hackathon
      daterange: March 23rd to April 12th
      assets:
        small_logo: './assets/img/small_logo.png'
        logo: './assets/img/logo.png'
      socials:
        discord: https://discord.hackquarantine.com/
        platform: https://platform.hackquarantine.com/
        workshops: https://workshops.hackquarantine.com/
        twitter: https://twitter.com/HackQuarantine
        facebook: https://www.facebook.com/HackQuarantine
        instagram: https://www.instagram.com/hackquarantine/
        linkedin: https://www.linkedin.com/company/hackquarantine/
        schedule: /schedule
        emails: 'https://cdn.forms-content.sg-form.com/2e1cc968-66fa-11ea-9912-5e37fcc2990c'


collections_dir: _collections

collections:
  - faq
